### ISSUE TITLE
colour vs color

### ISSUE THREAD

**Issue by MattWilcox** [percipioglobal/craft-colour-swatches#63]
The British version was working at some point, but checking 1.4.1.1 the swatches stopped appearing in the CMS when using the config file as...

```
return [
    // Predefined colors, fixed options [label, color, default (boolean)]
    'colours' => [
```

and I've had to switch back to the American

```
return [
    // Predefined colors, fixed options [label, color, default (boolean)]
    'colors' => [
```

**Comment by michtio** [comment]
Yeah that is correct @MattWilcox sorry for the confusion and this should've been flagged as breaking release or at least with a warning. We will go back to solely using the standard (international) way of using `color` in the plugin rather than the English version.

Our apologies for any inconveniences.

**Comment by MattWilcox** [comment]
Nope, all good as long as we know - Just took us unaware in this particular case. Cheers!

**Comment by MattWilcox** [comment]
FYI; the British is international. It's the American that is unique.

`The shorter one, color, is the preferred spelling in the United States. The rest of the English-speaking world uses the longer form, colour` 
https://www.grammarly.com/blog/color-colour/#:~:text=When%20choosing%20between%20color%20and,uses%20the%20longer%20form%2C%20colour.
