### ISSUE TITLE
Latest update breaks "migrate/all" over Craft console

### ISSUE THREAD

**Issue by mildlygeeky** [percipioglobal/craft-colour-swatches#70]
The schemaVersion in composer.json was updated even though the newest update to this plugin doesn't actually have/need any migrations. This is causing Craft to be confused and think that it has missed a migration, and require a manual visit to the CP in order to bring the site up.

The schemaVersion should only change if/when a new migration is also present on the plugin (furthermore, schemaVersion does not need to match the plugin version - Craft itself has a schemaVersion that is behind / not-in-sync with their Craft veron due to many Craft versions that do not require table migrations).

**Comment by bendesilva** [comment]
Also just ran into this issue. Just took down a website I was upgrading as I was also upgrading Craft at the same time, the CP wasn't accessible as a result and so had to restore a database backup and rollback the changes. Took a while to narrow it down to this plugin blocking `migrate/all`

**Comment by mildlygeeky** [comment]
@michtio can you please fix? This issue/update will take down any site that updates via CLI, and possibly also take down the CP itself if deployed alongside a Craft update.

**Comment by bengreenbank** [comment]
This is an issue for a few of our sites and is preventing one of our sites from going live. See issue reported on CraftCMS. https://github.com/craftcms/cms/issues/9860. Would be nice to get a fix for this soon.

**Comment by brandonkelly** [comment]
I’m not sure what the plugin could do to fix this at this point, besides adding a new dummy migration that doesn’t do anything, which would be a little lame.

As @mildlygeeky pointed out, running migrations from the Control Panel should get you passed this, or running this one plugin’s migrations individually rather than from `migrate/all`:

```bash
> php craft migrate/up --plugin=colour-swatches
```

I’ve also updated the `migrate/all` command to be defensive about this sort of situation, for the next release: https://github.com/craftcms/cms/issues/9860#issuecomment-925786882

**Comment by michtio** [comment]
Thank you @brandonkelly for fixing this within Craft Core! Much appreciated.

**Comment by michtio** [comment]
Fixed in Craft 3.7.14
