### ISSUE TITLE
Can't seem to limit to just the first color option in template

### ISSUE THREAD

**Issue by mediagirl** [percipioglobal/craft-colour-swatches#95]
I'm trying to return the first color for a field's selection in the template instead of looping through them:

```
	{% set style = block.styling.theme.color.one() %}
	{{ style .color }}
```

And I get this error:

```
Impossible to invoke a method ("one") on an array.
```

Shouldn't one() work in this case?

My color swatch field is inside a Matrix field and then inside a Supertable field.

**Comment by cookie10codes** [comment]
Hi @mediagirl,

We don't use the .one() notation in our plugin. You can update your piece of code like this in order to work:

```
{% set style = block.styling.theme.color[0] %}
{{ style .color }}
```

I hope this helped out your issue?

**Comment by michtio** [comment]
To clarify @mediagirl:

`.one()` notation can only be used on an Element Query, since our colour swatches are simply arrays you can't use `.one()` `.all()` `.count()` or any of those. You'd simply loop over the colours or you pick a specific one with the bracket notation as @cookie10codes mentioned here above.

**Comment by mediagirl** [comment]
I was able to get to the block.styling.theme.color[0] solution last night after Googling for a bit. 

I didn't realize one() was only on on an Element Query. Thank you for that tidbit!
